package com.necro.raid.dens.fabricgen.datagen;

import com.cobblemon.mod.common.CobblemonItems;
import com.necro.raid.dens.common.CobblemonRaidDens;
import com.necro.raid.dens.common.loot.function.GemTypeFunction;
import com.necro.raid.dens.common.loot.function.MaxMushroomsFunction;
import com.necro.raid.dens.common.loot.function.TeraShardsFunction;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.entries.NestedLootTable;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.providers.number.*;

import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;

public class LootTableGenerator extends SimpleFabricLootTableProvider {
    public LootTableGenerator(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(output, registryLookup, LootContextParamSets.CHEST);
    }

    @Override
    public void generate(BiConsumer<ResourceKey<LootTable>, LootTable.Builder> consumer) {
        consumer.accept(
            createKey("raid/type/gems"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(ConstantValue.exactly(1f))
                    .add(LootItem.lootTableItem(Items.AIR).apply(GemTypeFunction.apply()))
                    .build()
                )
        );

        consumer.accept(
            createKey("raid/feature/mega"),
            new LootTable.Builder()
        );

        consumer.accept(
            createKey("raid/feature/tera"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(ConstantValue.exactly(1f))
                    .add(LootItem.lootTableItem(Items.AIR).apply(TeraShardsFunction.apply()))
                    .build()
                )
        );

        consumer.accept(
            createKey("raid/feature/dynamax"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(ConstantValue.exactly(1f))
                    .add(LootItem.lootTableItem(Items.AIR).apply(MaxMushroomsFunction.apply()))
                    .build()
                )
        );

        consumer.accept(
            createKey("raid/tier/tier_one"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(2f, 4f))
                    .with(LootItem.lootTableItem(CobblemonItems.RED_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.YELLOW_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLACK_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MEDICINAL_LEEK)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.VIVICHOKE_SEEDS)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.IRON_NUGGET)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.STICK)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
                        .setWeight(5)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_two"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(3f, 6f))
                    .with(LootItem.lootTableItem(CobblemonItems.RED_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.YELLOW_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLACK_APRICORN)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.IRON_NUGGET)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_NUGGET)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.STICK)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.YELLOW_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLACK_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_APRICORN_SEED)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_XS)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_S)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(5)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_three"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(3f, 6f))
                    .with(LootItem.lootTableItem(Items.IRON_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_INGOT)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_S)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_M)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.HEALTH_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MUSCLE_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RESIST_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GENIUS_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CLEVER_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.SWIFT_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(NestedLootTable.lootTableReference(createKey("raid/type/gems"))
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_four"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(4f, 6f))
                    .with(LootItem.lootTableItem(Items.IRON_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.DIAMOND)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(1)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_M)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_L)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.HEALTH_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MUSCLE_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RESIST_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GENIUS_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CLEVER_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.SWIFT_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 3f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_CAPSULE)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(1)
                        .build())
                    .with(NestedLootTable.lootTableReference(createKey("raid/type/gems"))
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(10)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_five"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(4f, 8f))
                    .with(LootItem.lootTableItem(Items.IRON_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.DIAMOND)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_L)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_XL)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.HEALTH_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MUSCLE_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RESIST_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GENIUS_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CLEVER_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.SWIFT_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_CAPSULE)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(NestedLootTable.lootTableReference(createKey("raid/type/gems"))
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(10)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_six"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(6f, 8f))
                    .with(LootItem.lootTableItem(Items.IRON_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(Items.DIAMOND)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_L)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_XL)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RARE_CANDY)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.HEALTH_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MUSCLE_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RESIST_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GENIUS_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CLEVER_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.SWIFT_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(3f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_CAPSULE)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_PATCH)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(2)
                        .build())
                    .with(NestedLootTable.lootTableReference(createKey("raid/type/gems"))
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(10)
                        .build())
                .build()
            )
        );

        consumer.accept(
            createKey("raid/tier/tier_seven"),
            new LootTable.Builder()
                .pool(LootPool.lootPool().setRolls(UniformGenerator.between(8f, 10f))
                    .with(LootItem.lootTableItem(Items.IRON_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(Items.COPPER_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(Items.GOLD_INGOT)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(Items.DIAMOND)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(Items.NETHERITE_SCRAP)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(2)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_L)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.EXPERIENCE_CANDY_XL)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 6f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RARE_CANDY)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(1f, 2f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.HEALTH_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.MUSCLE_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RESIST_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GENIUS_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CLEVER_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.SWIFT_FEATHER)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(4f, 8f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_LEAF)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 4f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.RED_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.BLUE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.CYAN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.GREEN_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.PINK_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.WHITE_MINT_SEEDS)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_CAPSULE)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(10)
                        .build())
                    .with(LootItem.lootTableItem(CobblemonItems.ABILITY_PATCH)
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1f)))
                        .setWeight(5)
                        .build())
                    .with(NestedLootTable.lootTableReference(createKey("raid/type/gems"))
                        .apply(SetItemCountFunction.setCount(ConstantValue.exactly(2f)))
                        .setWeight(10)
                        .build())
                .build()
            )
        );
    }

    private ResourceKey<LootTable> createKey(String name) {
        return ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(CobblemonRaidDens.MOD_ID, name));
    }
}
